# Лабораторная работа №1. Настройка окружения и разведочный анализ данных.

## Цель работы

Подготовить структуру проекта и провести разведочный анализ данных. Результаты первой лабораторной работы будут использоваться в дальнейшем цикле работ.

In [23]:
import pandas as pd
import matplotlib as plt
import seaborn as sns
import numpy as np
import pickle

In [43]:
df = pd.read_csv('/home/mainuser/mf_project/data/car data.csv')

print("Размер данных:", df.shape)  
print("Столбцы:", list(df.columns))  
print("\nПервые 10 строк:")

df.head(10)

Размер данных: (301, 9)
Столбцы: ['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Driven_kms', 'Fuel_Type', 'Selling_type', 'Transmission', 'Owner']

Первые 10 строк:

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,0
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0

In [44]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Selling_type   301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [45]:
df['Car_Name'] = df['Car_Name'].astype('category')
df['Fuel_Type'] = df['Fuel_Type'].astype('category')
df['Selling_type'] = df['Selling_type'].astype('category')
df['Transmission'] = df['Transmission'].astype('category')

In [46]:
df['Owner'] = df['Owner'].astype('int8')

df['Year'] = df['Year'].astype('float32')
df['Selling_Price'] = df['Selling_Price'].astype('float32')
df['Present_Price'] = df['Present_Price'].astype('float32')
df['Driven_kms'] = df['Driven_kms'].astype('float32')

In [47]:
df.describe()

              Year  Selling_Price  Present_Price     Driven_kms       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627930       4.661296       7.628471   36947.207031    0.043189
std       2.891554       5.082811       8.642585   38886.882812    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.599998  500000.000000    3.000000

In [48]:
cat_features = df.select_dtypes(include=['category']).columns.to_list()
cat_features

['Car_Name', 'Fuel_Type', 'Selling_type', 'Transmission']

In [49]:
num_features = df.select_dtypes(include=['number']).columns.to_list()
num_features

['Year', 'Selling_Price', 'Present_Price', 'Driven_kms', 'Owner']

In [50]:
print("Пропущенные значения в каждом столбце:")
print(df.isnull().sum())  

duplicates = df.duplicated().sum()  
print(f"\nКоличество дубликатов: {duplicates}")

if duplicates > 0:
    df = df.drop_duplicates()  
    print(f"Удалили {duplicates} дубликатов")
else:
    print("Дубликатов нет")

Пропущенные значения в каждом столбце:
Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64

Количество дубликатов: 2
Удалили 2 дубликатов

In [51]:
for cat in cat_features:
    print(f'{cat} - numer of unique = {df[cat].nunique()}')

Car_Name - numer of unique = 98
Fuel_Type - numer of unique = 3
Selling_type - numer of unique = 2
Transmission - numer of unique = 2

In [52]:
for col in cat_features:
    print(f'Unique categories in {col}: {df[col].value_counts()}')

Unique categories in Car_Name: Car_Name
city             26
corolla altis    16
verna            14
brio             10
fortuner         10
                 ..
ignis             1
omni              1
land cruiser      1
s cross           1
vitara brezza     1
Name: count, Length: 98, dtype: int64
Unique categories in Fuel_Type: Fuel_Type
Petrol    239
Diesel     58
CNG         2
Name: count, dtype: int64
Unique categories in Selling_type: Selling_type
Dealer        193
Individual    106
Name: count, dtype: int64
Unique categories in Transmission: Transmission
Manual       260
Automatic     39
Name: count, dtype: int64

In [53]:
df = df.loc[df['Year'] > 0]
df = df.query('Selling_Price > 0')
df = df.query('Present_Price > 0')
df = df.query('Driven_kms >= 0')
df = df.query('Owner >= 0')

In [54]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 299 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       299 non-null    category
 1   Year           299 non-null    float32
 2   Selling_Price  299 non-null    float32
 3   Present_Price  299 non-null    float32
 4   Driven_kms     299 non-null    float32
 5   Fuel_Type      299 non-null    category
 6   Selling_type   299 non-null    category
 7   Transmission   299 non-null    category
 8   Owner          299 non-null    int8
dtypes: category(4), float32(4), int8(1)
memory usage: 11.7 KB

In [55]:
df['Car_Age'] = 2026 - df['Year'] 

print("Была добавлена 1 новая переменная")
print("Размер DataFrame после очистки:", df.shape)

print("\nПервые 5 строк с новым признаком:")
df[['Car_Name', 'Year', 'Car_Age']].head()

Была добавлена 1 новая переменная
Размер DataFrame после очистки: (299, 10)

Первые 5 строк с новым признаком:

  Car_Name    Year  Car_Age
0     ritz  2014.0     12.0
1      sx4  2013.0     13.0
2     ciaz  2017.0      9.0
3  wagon r  2011.0     15.0
4    swift  2014.0     12.0